### ISSUE TITLE
Stanford-specific Mirador deploy pattern

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/mirador_sul#11] opened 2017-02-22 20:12 UTC
@efahy has thought somewhat about this - needs more details.

**Comment by drh-stanford** [comment] 2017-02-23 19:47
also see https://github.com/sul-dlss/mirador_sul/issues/8

**Comment by drh-stanford** [comment] 2017-03-09 19:10
marking this a duplicate of #8...

**Closed by drh-stanford** 2017-03-09 19:10 UTC
Labels: ready
